"""add_driver_metrics

Revision ID: d13957478150
Revises: e6dbcfaf31ae
Create Date: 2025-12-06 13:11:29.041613

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d13957478150"
down_revision: Union[str, None] = "e6dbcfaf31ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drivers", sa.Column("physical_strength", sa.Integer(), nullable=True))
    op.add_column("drivers", sa.Column("bio_metrics", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drivers", "bio_metrics")
    op.drop_column("drivers", "physical_strength")
    # ### end Alembic commands ###
