"""add_laps_table

Revision ID: e6dbcfaf31ae
Revises: 863a6cc703f1
Create Date: 2025-12-06 10:51:19.004039

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6dbcfaf31ae"
down_revision: Union[str, None] = "863a6cc703f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "laps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=True),
        sa.Column("source_format", sa.String(length=50), nullable=True),
        sa.Column("driver_name", sa.String(length=100), nullable=False),
        sa.Column("track_name", sa.String(length=200), nullable=False),
        sa.Column("car_name", sa.String(length=100), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=True),
        sa.Column("lap_number", sa.Integer(), nullable=False),
        sa.Column("lap_time_ms", sa.Integer(), nullable=False),
        sa.Column("sector1_ms", sa.Integer(), nullable=True),
        sa.Column("sector2_ms", sa.Integer(), nullable=True),
        sa.Column("sector3_ms", sa.Integer(), nullable=True),
        sa.Column("sector4_ms", sa.Integer(), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=True),
        sa.Column("weather", sa.String(length=50), nullable=True),
        sa.Column("track_temp_c", sa.Float(), nullable=True),
        sa.Column("air_temp_c", sa.Float(), nullable=True),
        sa.Column("tire_compound", sa.String(length=50), nullable=True),
        sa.Column("conditions_json", sa.Text(), nullable=True),
        sa.Column("driver_id", sa.Integer(), nullable=True),
        sa.Column("track_id", sa.Integer(), nullable=True),
        sa.Column("kart_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=True),
        sa.Column("imported_at", sa.DateTime(), nullable=True),
        sa.Column("has_detailed_telemetry", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["kart_id"],
            ["karts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_laps_id"), "laps", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_laps_id"), table_name="laps")
    op.drop_table("laps")
    # ### end Alembic commands ###
